version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  transpiler_mock:
    build:
      context: ./transpiler_mock
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/transpiler/"] 
      interval: 10s
      timeout: 5s
      retries: 3

  service:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      # TRANSPILE_URL: http://transpiler_mock:8000/api/v1/transpiler/
      TRANSPILE_URL: https://bruno.ngrok.pro/api/v1/transpiler/
    depends_on:
      - db
      - transpiler_mock
    ports:
      - "8000:8000"

volumes:
  pgdata:
